### PR TITLE
update mix.lock to the latest version of auth_plug

### PR DESCRIPTION
**Pull request by SimonLab**
Update dependencies to keep badges green:

image

### CODE REVIEW

**Comment by SimonLab** [comment]
test timeout:
image

This is because of #18 (The tests are using the auth heroku app and this app is sleeping when the tests are running).
Now that Heroku is awake we can rerun the tests and they all should pass.
We should try to fix #18 to avoid the same issue in future

**Review by nelsonic — APPROVED** [review]
Thanks for updating @SimonLab 👍 
I think we'll need to release a new version to Hex.pm for Libraries.io to pick up the update. 💭

**Comment by nelsonic** [comment]
When attempting to publish, see the following warning:
```sh
The following licenses are not recognized by SPDX:
 * GNU GPL v2.0

Consider using licenses from https://spdx.org/licenses
```

**Review by nelsonic — APPROVED** [review]
@SimonLab thanks for updating. 🚀 

Package published to https://hex.pm/packages/rbac/0.7.2

**Pull request merged**
